/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Fichero_csv;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Ventana_MDI extends javax.swing.JFrame {

    public static ArrayList<String> credenciales;

    /**
     * Creates new form Ventana_MDI
     */
    public Ventana_MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        productoText = new javax.swing.JTextField();
        tipoText = new javax.swing.JTextField();
        costoText = new javax.swing.JTextField();
        caloriasText = new javax.swing.JTextField();
        grasaText = new javax.swing.JTextField();
        caloriasDeGrasaText = new javax.swing.JTextField();
        sodioText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        registroMenuItem = new javax.swing.JMenuItem();
        verMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setNextFocusableComponent(desktopPane);
        desktopPane.setSelectedFrame(jInternalFrame1);

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Registro Sopa");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setAutoscrolls(true);
        jInternalFrame1.setDoubleBuffered(true);
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registro.png"))); // NOI18N
        jInternalFrame1.setInheritsPopupMenu(true);
        jInternalFrame1.setName(""); // NOI18N
        jInternalFrame1.setNextFocusableComponent(desktopPane);
        jInternalFrame1.setVisible(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sopa.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Marca");

        jLabel3.setText("Producto");

        jLabel4.setText("Tipo");

        jLabel5.setText("Costo");

        jLabel6.setText("Calorias");

        jLabel7.setText("Grasa");

        jLabel8.setText("Calorias de Grasa");

        jLabel9.setText("Sodio");

        sodioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sodioTextKeyPressed(evt);
            }
        });

        jButton1.setText("Regristrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grasaText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caloriasText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productoText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(sodioText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(caloriasDeGrasaText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(costoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(caloriasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(grasaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(caloriasDeGrasaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sodioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 230, 220);
        try {
            jInternalFrame1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setTitle("Ver Archivo");
        jInternalFrame2.setAutoscrolls(true);
        jInternalFrame2.setDoubleBuffered(true);
        jInternalFrame2.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ver.png"))); // NOI18N
        jInternalFrame2.setInheritsPopupMenu(true);
        jInternalFrame2.setVisible(false);

        jButton3.setText("Abrir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Producto", "Tipo", "Costo", "Calorias", "Grasa", "Calorias de Sodio", "Sodio"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        desktopPane.add(jInternalFrame2);
        jInternalFrame2.setBounds(170, 50, 380, 320);
        try {
            jInternalFrame2.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        fileMenu.setMnemonic('f');
        fileMenu.setText("Proceso");

        registroMenuItem.setMnemonic('o');
        registroMenuItem.setText("Registrar");
        registroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(registroMenuItem);

        verMenuItem.setMnemonic('s');
        verMenuItem.setText("Ver");
        verMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(verMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuItemMouseClicked(evt);
            }
        });
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void exitMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            credenciales = cargarCredenciales();
        } catch (IOException ex) {
            Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            guardarCredenciales(marcaText.getText(), productoText.getText(), tipoText.getText(), costoText.getText(), caloriasText.getText(), grasaText.getText(), caloriasDeGrasaText.getText(), sodioText.getText());
        } catch (IOException ex) {
            Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void registroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroMenuItemActionPerformed
        JInternalFrame registro = jInternalFrame1;
        registro.setVisible(true);

    }//GEN-LAST:event_registroMenuItemActionPerformed

    private void verMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMenuItemActionPerformed
        JInternalFrame ver = jInternalFrame2;
        ver.setVisible(true);
    }//GEN-LAST:event_verMenuItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
        jInternalFrame1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyTyped


    private void sodioTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sodioTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                credenciales = cargarCredenciales();
            } catch (IOException ex) {
                Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                guardarCredenciales(marcaText.getText(), productoText.getText(), tipoText.getText(), costoText.getText(), caloriasText.getText(), grasaText.getText(), caloriasDeGrasaText.getText(), sodioText.getText());
            } catch (IOException ex) {
                Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_sodioTextKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".csv", "csv");
        abrir.setFileFilter(filtro);
        int selecionar = abrir.showOpenDialog(this);
        if (selecionar == abrir.APPROVE_OPTION) {
            String ruta = "src\\files\\sopas_en_lata.csv";
            File file = new File(ruta);
            try {
                BufferedReader br = new BufferedReader(new FileReader(file));
                String primeraLinea = br.readLine().trim();
                String[] nombreColumnas = primeraLinea.split(";");
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                modelo.setColumnIdentifiers(nombreColumnas);
                Object[] lineaTabla = br.lines().toArray();
                for (int i = 0; i < lineaTabla.length; i++) {
                    String linea = lineaTabla[i].toString().trim();
                    String[] dataRow = linea.split(";");
                    modelo.addRow(dataRow);
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jInternalFrame2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Marca");
        dtm.addColumn("Producto");
        dtm.addColumn("Tipo");
        dtm.addColumn("Costo");
        dtm.addColumn("Calorias");
        dtm.addColumn("Grasa");
        dtm.addColumn("Calorias de sodio");
        dtm.addColumn("Sodio");
        this.jTable1.setModel(dtm);
        int fila = jTable1.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        String ruta = "src\\files\\sopas_en_lata.csv";
        File file = new File(ruta);
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String primeraLinea = br.readLine().trim();
            String[] nombreColumnas = primeraLinea.split(";");
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setColumnIdentifiers(nombreColumnas);
            Object[] lineaTabla = br.lines().toArray();
            for (int i = 0; i < lineaTabla.length; i++) {
                String linea = lineaTabla[i].toString().trim();
                String[] dataRow = linea.split(";");
                modelo.addRow(dataRow);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventana_MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private static ArrayList<String> cargarCredenciales() throws IOException {
        ArrayList<String> credenciales = new ArrayList<>();
        try ( BufferedReader br = new BufferedReader(new FileReader("src\\files\\sopas_en_lata.csv"))) {
            br.readLine();
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] campos = linea.split(";");
                boolean add = credenciales.add(campos[0] + ";" + campos[1] + ";" + campos[2] + ";" + campos[3] + ";" + campos[4] + ";" + campos[5] + ";" + campos[6] + ";" + campos[7]);
            }
        }
        return credenciales;
    }

    private void guardarCredenciales(String marca, String producto, String tipo, String costo, String calorias, String grasa, String caloriasDeSodio, String sodio) throws IOException {
        credenciales = cargarCredenciales();
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/error.gif"));

        if (marca.isBlank()) {
            JOptionPane.showMessageDialog(marcaText, "Marca no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);

            System.out.println("Marca no puede estar vacio");
            return;
        }
        if (producto.isBlank()) {
            JOptionPane.showMessageDialog(productoText, "Producto no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Producto no puede estar vacio");
            return;
        }
        if (tipo.isBlank()) {
            JOptionPane.showMessageDialog(tipoText, "Tipo no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Tipo no puede estar vacio");
            return;
        }
        if (costo.isBlank()) {
            JOptionPane.showMessageDialog(costoText, "Costo no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Costo no puede estar vacio");
            return;
        }
        if (calorias.isBlank()) {
            JOptionPane.showMessageDialog(caloriasText, "Calorias no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Calorias no puede estar vacio");
            return;
        }
        if (grasa.isBlank()) {
            JOptionPane.showMessageDialog(grasaText, "Grasa no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Grasa no puede estar vacio");
            return;
        }
        if (caloriasDeSodio.isBlank()) {
            JOptionPane.showMessageDialog(caloriasDeGrasaText, "Calorias de Sodio no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Calorias de Sodio no puede estar vacio");
            return;
        }
        if (sodio.isBlank()) {
            JOptionPane.showMessageDialog(sodioText, "Sodio no puede estar Vacio", "Dato Invalido", JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println("Sodio no puede estar vacio");
            return;
        }

        try ( BufferedWriter bw = new BufferedWriter(new FileWriter("src\\files\\sopas_en_lata.csv"))) {
            bw.write("Marca;Producto;Tipo;Costo;Calorias;Grasa;Calorias de Sodio;Sodio\n");
            for (String credencial : credenciales) {
                bw.write(credencial.replace(";", ";") + "\n");
            }
            bw.write(marca + ";" + producto + ";" + tipo + ";" + costo + ";" + calorias + ";" + grasa + ";" + caloriasDeSodio + ";" + sodio + "\n");
            credenciales.add(marca + ";" + producto + ";" + tipo + ";" + costo + ";" + calorias + ";" + grasa + ";" + caloriasDeSodio + ";" + sodio);
        }
        System.out.println("Registrado");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caloriasDeGrasaText;
    private javax.swing.JTextField caloriasText;
    private javax.swing.JTextField costoText;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField grasaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField marcaText;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField productoText;
    private javax.swing.JMenuItem registroMenuItem;
    private javax.swing.JTextField sodioText;
    private javax.swing.JTextField tipoText;
    private javax.swing.JMenuItem verMenuItem;
    // End of variables declaration//GEN-END:variables
}
